name: sue
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - accelerate==1.2.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annoy==1.17.3
    - appdirs==1.4.4
    - attrs==24.2.0
    - beautifulsoup4==4.12.3
    - bs4==0.0.2
    - certifi==2024.7.4
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - datasets==3.2.0
    - decorator==4.4.2
    - diffusers==0.32.1
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - dreamsim==0.2.1
    - dukpy==0.5.0
    - einops==0.8.0
    - filelock==3.15.4
    - fonttools==4.53.1
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - ftfy==6.3.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - h5py==3.11.0
    - huggingface-hub==0.27.0
    - idna==3.7
    - imageio==2.36.0
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==8.5.0
    - iniconfig==2.0.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - lightning==2.4.0
    - lightning-utilities==0.11.8
    - llvmlite==0.43.0
    - lpip==1.0.7
    - lpips==0.1.4
    - markupsafe==2.1.5
    - matplotlib==3.9.1
    - moviepy==1.0.3
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - munkres==1.1.4
    - networkx==3.3
    - ninja==1.11.1.3
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu12==12.1.105
    - open-clip-torch==2.29.0
    - packaging==24.1
    - pandas==2.1.3
    - peft==0.13.2
    - pillow==10.4.0
    - pluggy==1.5.0
    - pot==0.9.4
    - proglog==0.1.10
    - propcache==0.2.0
    - protobuf==4.25.0
    - psutil==5.9.6
    - pyarrow==18.0.0
    - pycparser==2.22
    - pynndescent==0.5.13
    - pypac==0.16.5
    - pyparsing==3.1.2
    - pytest==8.3.1
    - python-dateutil==2.9.0.post0
    - pytorch-adapt==0.0.83
    - pytorch-ignite==0.5.1
    - pytorch-lightning==2.4.0
    - pytorch-metric-learning==1.6.3
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - regex==2024.5.15
    - requests==2.32.3
    - requests-file==2.1.0
    - safetensors==0.4.3
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - sentence-transformers==3.0.1
    - sentencepiece==0.2.0
    - sentry-sdk==1.35.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - soundfile==0.12.1
    - soupsieve==2.6
    - sympy==1.13.0
    - threadpoolctl==3.5.0
    - timm==1.0.13
    - tldextract==5.1.3
    - tokenizers==0.19.1
    - torch==2.3.1
    - torchaudio==2.1.0
    - torchmetrics==0.9.3
    - torchmimic==0.0.7
    - torchvision==0.18.1
    - tqdm==4.66.4
    - transformers==4.42.4
    - triton==2.3.1
    - typing-extensions==4.12.2
    - tzdata==2023.3
    - umap-learn==0.5.6
    - urllib3==2.2.2
    - wandb==0.16.0
    - wcwidth==0.2.13
    - xxhash==3.5.0
    - yarl==1.17.1
    - zipp==3.21.0
